application: mobdigest
version: 1
runtime: python27
api_version: 1
threadsafe: true
  
inbound_services:
- mail

handlers:
- url: /report/stats
  script: main.application
  login: admin    
- url: /.*
  script: main.application
  login: admin  
- url: /_ah/mail/.+
  script: main.application
  login: admin

  


